name: Docker Image CI

on:
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: artis3n/docker-ubuntu2104-ansible

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Hadolint
        run: make lint

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: docker/setup-buildx-action@v1

    - name: Cache
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Install Goss
      uses: e1himself/goss-installation-action@v1.0.1
      with:
        version: 'v0.3.13'

    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: ${{ env.IMAGE_NAME }}:test
        load: true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Test the Docker image
      run: dgoss run -it --rm --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro ${{ env.IMAGE_NAME }}:test
